version: '3.7'
services:
  server:
    image: yakwilik/mrga_backend@sha256:b83d2b8943b917d60a42e1a7c7c54c4feabcfa9442d7139e9e5aab763f874c91

    command: bash -c "mkdir -p build
              &&
            cd build && cmake ..
              &&
            cmake --build .
              &&
            ./project/server/server"
    working_dir: '/project'
    volumes:
      - "${PWD}/:/project/"
    ports:
      - "8080:8080"
    networks:
      service-network:

  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: "mashadb"
      POSTGRES_USER: "mashapg"
      POSTGRES_PASSWORD: "mashapg"
    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      service-network:
        ipv4_address: 10.0.0.10

    ports:
      - "5432:5432"

networks:
  service-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.1
    



