// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_PartyTime();
Q_GHS_KEEP_REFERENCE(qml_register_types_PartyTime);

class PartyTimePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    PartyTimePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_PartyTime;
        Q_UNUSED(registration);
    }
};



#include "myappplugin_PartyTimePlugin.moc"
